apiVersion: v1
data:
  DEBUG: ' '
  JAVA_OPTIONS: -Xms1024M -Xmx1024M -XX:+UseG1GC -XX:+PrintGCApplicationStoppedTime
    -XX:+PrintGCApplicationConcurrentTime -XX:+PrintSafepointStatistics -XX:PrintSafepointStatisticsCount=1
    -verbose:gc -Xloggc:/data/inc/logs/gc.log -XX:+UseGCLogFileRotation -XX:GCLogFileSize=20M
    -XX:NumberOfGCLogFiles=12 -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution
    -XX:+PrintHeapAtGC -Dahas.namespace=prod -Dproject.name=saf-web-allinone -XX:+UnlockExperimentalVMOptions
    -XX:+UseCGroupMemoryLimitForHeap -XX:ParallelGCThreads=4
  appid: saf-sample-allinone-web
  denv: pro
  sentinel_server: ' '
kind: ConfigMap
metadata:
  labels:
    app: saf-sample-allinone-web-prod
  name: saf-sample-allinone-web-prod
  namespace: inc
